FROM lsiobase/ubuntu:focal

# set version label
ARG BUILD_DATE
ARG VERSION
ARG CHROMEDRIVER_VERSION
ENV USING_DOCKER 'TRUE'
ENV LOG_FILE 'FALSE'
# latest is 86
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="matweaver7"

ARG BUILD_PACKAGES="\
	build-essential \
	git \
	wget \
	gnupg2 \
	unzip \
	python3-dev \
	python3-pip"

# packages as variables
ARG RUNTIME_PACKAGES="\
	cron \
	python3"

RUN \
 apt update && \
 echo "**** install build packages ****" && \
 apt-get install -y \
 	--no-install-recommends \
	$BUILD_PACKAGES && \
 echo "**** install runtime packages ****" && \
 apt-get install -y \
 	--no-install-recommends \
	$RUNTIME_PACKAGES && \
 echo "**** install chromedriver ****" && \
 mkdir -p /app/chromedriver && \
 if [ -z ${CHROMEDRIVER_VERSION+x} ]; then \
	CHROMEDRIVER_VERSION=$(curl -sX GET "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"); \
 fi && \
 curl -o \
 	/tmp/chromedriver_linux64.zip -L \
   "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" && \
 unzip /tmp/chromedriver_linux64.zip \
   -d /app/chromedriver && \
 ln -s /app/chromedriver/chromedriver /usr/bin && \
 echo "**** install KSL-Notifications ****" && \
 mkdir -p /app/ksl-notifications && \
 git clone https://github.com/matweaver7/ksl-notifications \
  /app/ksl-notifications && \
 echo "**** install pip packages ****" && \
 cd /app/ksl-notifications && \
 pip3 install -r requirements.txt && \
 echo "**** prep chrome ****" && \
 wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
 echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
 echo "**** some cleanup ****" && \
 apt-get purge -y --auto-remove \
	$BUILD_PACKAGES && \
 echo "**** install chrome ****" && \
 apt update && \
 apt-get install -y google-chrome-stable && \
 echo "**** last cleanup ****" && \
 rm -rf \
	/root/.cache \
	/tmp/*

# copy local files
COPY root/ /